### ISSUE TITLE
Nuxt3 - Cannot read properties of undefined (reading '$gb')

### ISSUE THREAD

**Issue by Dharmang92** [growthbunker/vuedarkmode#71]
Console error-

Env -
Windows 10
VSCode
Nuxt 3.0.0-rc.9 with Nitro 0.5.3
Vue 3
Yarn

[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading '$gb')
  at Object.install (C:\Users\Dharmang\Desktop\resonate-nuxt\node_modules\@growthbunker\vuedarkmode\dist\vuedarkmode.ssr.js:3138:22)
  at Object.use (C:\Users\Dharmang\Desktop\resonate-nuxt\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:4329:28)
  at C:/Users/Dharmang/Desktop/resonate-nuxt/plugins/vuedarkmode.ts:6:18
  at fn (C:/Users/Dharmang/Desktop/resonate-nuxt/node_modules/nuxt/dist/app/nuxt.mjs:128:27)
  at Object.callAsync (/C:/Users/Dharmang/Desktop/resonate-nuxt/node_modules/unctx/dist/index.mjs:49:19)
  at callWithNuxt (C:/Users/Dharmang/Desktop/resonate-nuxt/node_modules/nuxt/dist/app/nuxt.mjs:130:23)
  at applyPlugin (C:/Users/Dharmang/Desktop/resonate-nuxt/node_modules/nuxt/dist/app/nuxt.mjs:74:29)
  at Module.applyPlugins (C:/Users/Dharmang/Desktop/resonate-nuxt/node_modules/nuxt/dist/app/nuxt.mjs:84:11)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async createNuxtAppServer (C:/Users/Dharmang/Desktop/resonate-nuxt/node_modules/nuxt/dist/app/entry.mjs:30:7)

**Comment by Frier03** [comment]
Same error
